architecture: standalone

auth:
  enabled: false

master:
  persistence:
    enabled: true
    size: 256Mi
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

metrics:
  enabled: false