apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topics-init
  namespace: jobradar
  labels:
    app.kubernetes.io/part-of: jobradar
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-topics
          image: apache/kafka:4.2.0
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for Kafka..."
              until /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka:9092 \
                --list > /dev/null 2>&1; do
                sleep 5
              done
              echo "Creating topics..."
              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka:9092 \
                --create --if-not-exists \
                --topic raw-offers \
                --partitions 3 \
                --replication-factor 1
              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka:9092 \
                --create --if-not-exists \
                --topic scored-offers \
                --partitions 3 \
                --replication-factor 1
              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka:9092 \
                --create --if-not-exists \
                --topic alerts \
                --partitions 1 \
                --replication-factor 1
              echo "Topics created:"
              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka:9092 \
                --list